name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches-ignore: ["main"]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          # depth=2 is needed by build_then_push.sh
          fetch-depth: 2
          persist-credentials: false
      - name: Docker toolchains
        run: docker version
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the docker images
        run: |
          tag=$(git rev-parse --short HEAD)               &&
          repo_tag=sammyne/gramine-quickstart-sc2.12:$tag &&
          docker build -t  $repo_tag .                    &&
          docker push $repo_tag
